SELECT *
  FROM A_PEOPLE
 WHERE LOWER(NVL((A_PEOPLE.LASTNAME), ' ')) LIKE '%'||LOWER(NVL((:LASTNAME), '%'))||'%'
   AND LOWER(NVL((A_PEOPLE.FIRSTNAME), ' ')) LIKE '%'||LOWER(NVL((:FIRSTNAME), '%'))||'%'